services:
  # Local Redis Service
  redis:
    image: redis:7-alpine
    container_name: digitaltwin_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
  sqlserver:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: digitaltwin_sql
      ports:
        - "1433:1433"
      environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD:  ${DB_PASSWORD}
      restart: unless-stopped
      volumes:
        - sql_data:/var/opt/mssql
      
  # Backend FastAPI Service
  backend:
    build:
      context: ./DigitalTwin.API
      dockerfile: Dockerfile
    container_name: digitaltwin_backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - sqlserver
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - backend_uploads:/app/uploads
    restart: unless-stopped

  # Frontend Nginx Service
  frontend:
    build:
      context: ./DigitalTwin.Client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8000
    container_name: digitaltwin_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    env_file:
      - ./.env
    volumes:
      - ./db/init.sql:/init.sql
    command: >
      /bin/bash -c "
      until /opt/mssql-tools/bin/sqlcmd
      -S sqlserver
      -U ${DB_USER}
      -P ${DB_PASSWORD}
      -Q 'SELECT 1';
      do sleep 5;
      done;

      /opt/mssql-tools/bin/sqlcmd
      -S sqlserver
      -U ${DB_USER}
      -P ${DB_PASSWORD}
      -i /init.sql
      "
    restart: "no"

volumes:
  redis_data:
  backend_uploads:
  sql_data:
